services:
  db:
    image: postgres:15
    container_name: pr_review_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pr_review
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: alpine:latest
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
      context: .
    container_name: pr_review_app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/pr_review?sslmode=disable
      PORT: 8080

volumes:
  pg_data:
