services:
  db:
    image: postgres:15
    container_name: pr_review_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pr_review
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
